############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About us"
url = "/about"
weight = 2

[[main]]
name = "People"
url = "/people"
weight = 3

[[main]]
name = "Research"
url = "/research"
weight = 4

[[main]]
name = "News"
url = "/news"
weight = 5

[[main]]
name = "Events"
url = "/events"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "About us"
url = "/about"
weight = 1

[[footer]]
name = "Research"
url = "/research"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3
